[package]
name = "brkt"
version = "1.0.0"
authors = []

[addresses]
brkt_addr='0000000000000000000000000000000000000000000000000000000000000000'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
